Repository makerdao/dss-exec-lib, pull requests merged in 2021-02, with the labels that each got.

#51 Fix to work with official latest release
  test.sh
Labels: Priority: High, Status: Ready for Review

#55 Remove most of the functions from DssActions and use them directly fr…
  src/DssAction.sol
  src/DssExecLib.sol
  src/MathLib.sol
  src/test/DssAction.t.sol
  src/test/DssExec.t.sol
  src/test/DssTestAction.sol
Labels: Status: Ready for Review

#62 feat: Add config
  Makefile
  config.json
  test.sh
Labels: Priority: Medium, Status: Ready for Review

#59 feat: Added ERC20 DAI payment method
  README.md
  src/DssExecLib.sol
  src/test/DssAction.t.sol
  src/test/DssTestAction.sol
Labels: Priority: Medium, Status: Ready for Review

#63 Workaround to be able to compile with optimization on 0.6.11 and impo…
  .travis.yml
  Makefile
  allow-optimize.sh
  build.sh
  shell.nix
  test.sh
Labels: Priority: High, Status: Ready for Review

#64 First step to decouple action from the lib implementation + renaming …
  src/DssAction.sol
  src/test/DssExec.t.sol
  src/test/DssTestAction.sol
Labels: Priority: Critical
